import { useEffect } from "react";


const TermsConditionsDriver = () => {

  const h2 = "text-lg font-semibold"
  useEffect(() => {
    window.scrollTo({
      top: 0,
    });
  }, [])

  return (
    <div className='max-w-full bg-gray-100 flex items-center  justify-center '>
      <div className="md:w-1/2 p-5 md:p-0">
        <h1 className="md:text-2xl  text-xl font-bold  text-center mb-5 mt-5">Terms and Conditions</h1>
        <div className="opacity-75 text-xs flex flex-col gap-3 mb-5">
          <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
          <p>By clicking on the “I ACCEPT” button or by using Mybuggy Cab services, You are consenting to be bound by these User Terms.</p>
          <p>PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE USER TERMS BEFORE YOU USE THE SITE.</p>
          <p>If You do not accept any of the User Terms, then please do not use the Application of Mybuggy Cabs or avail any of the services being provided therein.</p>
          <p>YOUR AGREEMENT TO THESE USER TERMS SHALL OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND Mybuggy CABS IN RESPECT OF THE USE AND SERVICES OF THE SITE.</p>
          <p>Your acceptance of the User Terms shall be deemed to include your acceptance of the privacy policy. By accepting these User Terms, You also allow Mybuggy Cabs to send you promotional emails and SMS alerts from time to time.</p>
          <h2 className={h2} >1. DEFINITIONS</h2>
          <p>All of the defined and capitalized terms in these User Terms will have the meaning assigned to them here below:-</p>
          <p>(i) “Account” shall mean the account created by the Customer on the Application for availing the Services provided by Mybuggy Cabs.</p>
          <p>(ii) “Additional Fee” shall mean any toll duty, inter-state taxes, etc. as may not be included in the Fare or not already paid as a part of the Total Ride Fee but payable to any third party / government authorities for undertaking the Ride under Applicable Law.
          </p>
          <p>(iii) “Applicable Laws” shall mean and include all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives and orders of any governmental authority, tribunal, or a court of USA.</p>
          <p>(iv) “Application” shall mean the mobile application “Mybuggy CabsCabs” updated by Mybuggy Cabs from time to time.
          </p>
          <p>(v) “Convenience Fee”/” Access Fee” shall mean the fee payable by the Customer to Mybuggy Cabs for the Service i.e., for availing the technology services offered by Mybuggy Cabs, door to door service, wi-fi access, customer support and cashless payment options. Convenience Fee shall be chargeable on every booking made through the Application. The Convenience Fee shall be exclusive of all applicable taxes on the Convenience Fee, if any.
          </p>
          <p>(vi) “Cancellation Fee” shall mean the Fare and Convenience Fee payable towards cancellation of a Ride by a Customer in terms of Clause 7 of these User Terms and the Cancellation Terms and Conditions available at Mybuggy Cab. The Cancellation Fee shall be exclusive of all applicable taxes on the Cancellation Fee, if any.</p>
          <p>(vii) “City of Operation” shall mean a city in which the Customers and Drivers avail and render the transportation services respectively. For clarity, the services rendered by the Drivers and availed by the Customers shall be in the same city.
          </p>
          <p>(viii) “Customer/ You” means a person who has an Account on the Application.
          </p>
          <p>(ix) “Driver” shall mean and include such individuals as may be evaluated, appointed and trained by an operator associated with us to provide the transportation services on its behalf and persons who are registered with Mybuggy Cabs and own such Vehicles with necessary city taxi permits and other applicable transport vehicle permits and licenses to provide transportation services within the City of Operation.
          </p>
          <p>(xi) “Fare” shall mean such amount in USA, which is reflected on the Application, as the fare payable for the specific Ride performed by a Driver. The Fare shall be exclusive of all applicable taxes on the Fare, if any.</p>
          <p>(xii) “Force Majeure Event” shall mean any event arising due to any cause beyond the reasonable control of Mybuggy Cabs.
          </p>
          <p>(xiii) “Mybuggy Cabs” or “us” or “we” or “our” shall mean ANI Technologies Private Limited, a company incorporated under the provisions of the Companies Act, 1956 and having its registered office at, which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include all its successors, affiliates and permitted assigns.</p>
          <p>(xiv) “Registration Data” shall mean and may include the present, valid, true and accurate name, email ID, phone number and such other information as may be required by Mybuggy Cabs from the Customer from time to time for registration on the Application.
          </p>
          <p>(xv) “Ride” shall mean the travel in the Vehicle by the Customer facilitated through the Site.
          </p>
          <p> (xvi) “Service(s)” means the facilitation of the services by Mybuggy Cabs through the Application or via a telephone request at the call center of Mybuggy Cabs, or booking on the Site.</p>
          <p>(xvii) “Site” shall mean the Application and the website https://www.Mybuggy Cabscabs.com/ operated by Mybuggy Cabs or any other software that enables the use of the Application or such other URL as may be specifically provided by Mybuggy Cabs.
          </p>
          <p>(xviii) “Substitute Vehicle” shall mean another vehicle arranged for transporting the Customers to his/her destination, in the event of a Vehicle breakdown.
          </p>
          <p>(xix) “Total Ride Fee” shall mean and include the Fare, the Convenience Fee or Access Fee, the Cancellation Fee and Additional Fee and taxes as may be applicable from time to time.
          </p>
          <p>(xx) “T&Cs” and “User Terms” shall mean these Customer terms and conditions.
          </p>
          <p> (xxi) “TPSP” shall mean a third party service provider.</p>
          <p>(xxii) “Vehicle” shall mean a motor cab as defined under the Motor Vehicles Act,1988.</p>
          <p>(xxiii) – Drivers may install windshield camera for safety reason but it has to be as per state law.</p>
          <p>(xxiv) Drivers MUST have first-aid box for emergency first aid treatment.</p>
          <p>(xxv) Driver will handle your package with care during delivery.
          </p>
          <p>(xxvi) Customer need to pay for products being purchased at stores, Easy Taxi Drivers would be only responsible for delivery at your drop off address.</p>
          <h2 className={h2}>2. ELIGIBILITY</h2>
          <p>You will be “Eligible” to use the Services only when You fulfil all of the following conditions:</p>
          <p> (i) You have attained at least 21 (Twenty One) years of age.</p>
          <p>(ii) You are competent to enter into a contract under the Applicable Laws.</p>
          <p>If You reside in a jurisdiction that restricts the use of the Service because of age, or restricts the ability to enter into contracts such as this User Terms due to age, You must abide by such age limits.
          </p>
          <p>3. REGISTRATION AND ACCOUNT:-
            3.1 You understand and acknowledge that You can register on the Site only after complying with the requirements of this Clause 3 and by entering Your Registration Data.</p>
          <p>3.2 You shall ensure that the Registration Data provided by You is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by You.</p>

          <p>3.3 You are solely responsible for maintaining the confidentiality of Your Registration Data and will be liable for all activities and transactions that occur through Your Account, whether initiated by You or any third party. Your Account cannot be transferred, assigned or sold to a third party. We shall not be liable for any loss that You may incur as a result of someone else using Your password or Account, either with or without Your knowledge.</p>

          <p>3.4 We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period, if We have a reason to believe that the Registration Data or any other data provided by You is incorrect or false, or that the security of Your Account has been compromised in any way, or for any other reason We may find just or equitable.</p>

          <p>3.5 Except for the Registration Data or any other data submitted by You during the use of any other service offered through Site (“Permitted Information”), Mybuggy Cabs does not want You to, and You should not, send any confidential or proprietary information to Mybuggy Cabs on the Site or otherwise, unless otherwise is required by Applicable Laws. In accepting these User Terms You agree that any information or materials that You or individuals acting on Your behalf provide to Mybuggy Cabs other than the Permitted Information will not be considered confidential or proprietary.</p>

          <p>3.6 It is Your responsibility to check to ensure that You download the correct application for Your device. We are not liable if You do not have a compatible mobile device or if You download the wrong version of the Application for Your mobile device. We reserve the right to terminate the Service and the use of the Application should You be using the Service or Application with an incompatible or unauthorized device.</p>

          <p>3.7 We allow You to open only one Account in association with the Registration Data provided by You. In case of any unauthorized use of Your Account please immediately reach Us at ____________________________________________.</p>

          <p>3.8 In case, You are unable to access Your Account, please inform Us at ________________________ and make a written request for blocking Your Account. We will not be liable for any un-authorised transactions made through Your Account prior to the expiry of 72 (seventy-two) hours after You have made a request in writing for blocking Your Account, and shall not have any liability in case of Force Majeure Event.</p>

          <h2 className={h2}>4. SERVICES:-</h2>
          <p>4.1. Mybuggy Cabs shall procure reasonable efforts to bring You into contact with a Driver, subject to the availability of Driver in or around Your location at the moment of Your request for such services.</p>

          <p>4.2. By using the Application or the Service, You further agree that:-</p>

          <p>(i) You will only use the Service or download the Application for Your sole, personal use and will not resell or assign it to a third party;</p>

          <p>(ii) You will not use an account that is subject to any rights of a person other than You without appropriate authorization;</p>

          <p>(iii) You will not use the Service or Site for unlawful purposes;</p>

          <p>(iv) You will not try to harm the Service, Site or our network in any way whatsoever;</p>

          <p>(v) You will provide Mybuggy Cabs with such information and documents which Mybuggy Cabs may reasonably request;</p>

          <p>(vi) You will only use an authorized network to avail the Service;</p>

          <p>(vii) You are aware that when requesting Services, whether by message, via Site or calling the call center of Mybuggy Cabs, standard messaging charges, data charges, voice charges, as applicable, of the Your and Our phone network service providers, will apply;</p>

          <p>(viii) You will comply with all Applicable Law from Your country of domicile and residence and the country, state and/or city in which You are present while using the Site or Service; and (ix) You are aware of and shall comply with the Information Technology Act, 2000 and the rules, regulations and guidelines notified thereunder.</p>

          <p>(ix) You will not request anything which is not ethical or does not follow Pennsylvania and USA laws.</p>

          <p>4.3. Mybuggy Cabs reserves the right to immediately terminate the Service and the use of the Application in the event of non-compliance with any of the above requirements. Further, Mybuggy Cabs will store the information provided by You or record your calls for contacting You for all Service related matters. You shall promptly inform Mybuggy Cabs on any change in the information provided by You.</p>

          <p>4.4. Mybuggy Cabs or an authorized representative of Mybuggy Cabs, shall provide information regarding services, discounts and promotions provided by Mybuggy Cabs or a TPSP to You on the Mybuggy Cabs App or by way of an SMS or email to Your registered mobile number/registered email ID. You also have the option to discontinue receiving such information at any point of time. To discontinue receiving such information, You may at any point of time visit the specific link provided in the Site to discontinue the same.</p>

          <p>4.5. Mybuggy CABS WILL BE ENTITLED TO PROCESS AND TRANSFER YOUR INFORMATION AS AND WHEN IT DEEMS FIT AND IT MAY STORE OR TRANSFER YOUR INFORMATION IN A SERVER OUTSIDE USA OR THE COUNTRY WHERE YOU ARE LOCATED IN ORDER TO PERFORM Mybuggy CABS’S OBLIGATIONS UNDER THESE CUSTOMER T&C.</p>

          <p>4.6. You agree to grant Mybuggy Cabs a non-exclusive, worldwide, perpetual, irrevocable, royalty- free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in your information, in any media now known or not currently known, with respect to Your information. YOU AGREE AND PERMIT Mybuggy CABS TO SHARE YOUR INFORMATION AND/OR PERMITTED INFORMATION, WITH THIRD PARTIES.</p>

          <p>4.7. You agree and permit Mybuggy Cabs to share any information provided by You with third parties in order to facilitate provision of certain value-added services offered by such third parties to You and/or to provide certain value-added services to You by Mybuggy Cabs. You hereby expressly consent to receive communications from Mybuggy Cabs/ third parties offering value-added services to You through Your registered phone number and/or e-mail id and/or the Site. You agree that You will not hold Mybuggy Cabs responsible for any such communications received from third parties, nor will any such communication amount to spam, unsolicited communication.</p>

          <p>4.8. Mybuggy Cabs will be entitled to enter into any tie-up in terms of joint-venture or otherwise with any other institution engaged in the business of providing services analogous and/or similar to those herein contained. In such case, depending upon the modality and the mechanism as may be devised, You will be provided with the services by Mybuggy Cabs jointly and/or severally with the party/ies in joint venture. You hereby give Your irrevocable consent and permission to such a tie-up. In the event of such a tie-up, the terms and conditions herein contained will, mutatis mutandis, become applicable in respect of such tie-up arrangement also.</p>

          <p>4.10. In the event Mybuggy Cabs provides You any device as a part of the Services including but not limited to ________________________, You shall comply with the following. ‘GO ____________________________’ means a connected car platform using multiple devices in-car and cloud technology platform owned and operated by ___________, which endeavours to provide an interactive experience to You –</p>

          <p>(i) You shall not tamper, pilfer or misuse the ________ Device(s) or allow, induce orassist a third party to indulge in such activity.</p>

          <p>(ii) You shall not transcribe, distribute, download, store, duplicate and reproduce the content forming part of the Mybuggy CABS Device(s) (“Content”), in whole or in part, through any medium including, but not limited to, tape, disc, hard disk, computer system, or other electronic recording or transmission device.</p>

          <p>(iii) You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party, in any way, the Mybuggy CABS Device(s) and/or any Content;</p>

          <p>(ii) modify or make derivative works from the Content;</p>

          <p>(iii) create Internet “links” to the Content or “frame” or “mirror” any Content on any other server or wireless or internet-based device;</p>

          <p>(iv) reverse engineer or access the Mybuggy CABS Device(s) and/or Content in order to (a) design or build a competitive product or service,</p>

          <p>(b) design or build a product using similar ideas, features, functions or graphics of the Mybuggy CABS Device(s) and/or Content, or</p>

          <p>(c) copy any ideas, features, functions or graphics of the Mybuggy CABS Device(s) and/or Content, or</p>

          <p>(v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Mybuggy CABS Device and/or Content</p>

          <p>(iv) You shall not use the Mybuggy CABS Device(s) for any illegal or unlawful purposes including but not limited to playing / watching pornographic content on the Mybuggy CABS Device and shall use the Mybuggy CABS Device(s) solely for purposes determined by Mybuggy Cabs and strictly in accordance with these User Terms.</p>

          <p>You shall solely be responsible and liable for any Mybuggy Cab stations of law committed by You and misuse of the Mybuggy CABS Device(s), if any, with the Mybuggy CABS Device(s).</p>

          <p>(v) You shall ensure that the Mybuggy CABS Device(s) is maintained in Your possession in a proper manner. Mybuggy Cabs may, at its sole discretion, charge such amounts from You as may be determined by Mybuggy Cabs for use of the Mybuggy CABS Device(s) by You.</p>

          <p>(vi) In the event the Mybuggy CABS Device(s) is not functioning properly or if there is any technical or safety issue in relation to the Mybuggy CABS Device(s), You shall immediately inform the Driver about any such issue.</p>

          <p>(vii) You shall use the Mybuggy CABS Device(s) with due care and caution and not do anything or permit anything to be done that may cause damage to the Mybuggy CABS Device(s). If the Mybuggy CABS Device(s) is damaged and is not repairable due to any act of You, You shall pay amounts to Mybuggy Cabs, as may be determined by Mybuggy Cabs. If You fail or are unable to pay the amounts determined by Mybuggy Cabs, Mybuggy Cabs shall be entitled to suspend / terminate Your Account with Mybuggy Cabs without prejudice to Mybuggy Cab’s rights under these User Terms and under Applicable Laws.</p>

          <p>4.11. In the event Mybuggy Cabs provides You any Vehicle for testing as a part of the Services including but not limited to Mybuggy CABS CARS (“Mybuggy CABS CARS”), You shall comply with the following: (i) You will ensure no damage is caused to the Vehicle in the course of your use/ testing the same and the same is returned in good condition; (ii) You agree that Mybuggy Cabs can charge you for any such damage caused to the Vehicle while being used by You; (iii) You will not use the test Vehicle only for the purpose of testing and shall not exceed the predetermined time/ distance.</p>

          <p>4.12. In the event of breakdown of the Vehicle, which is beyond repair, before completion of the Ride, Mybuggy Cabs on a best effort basis and at its sole discretion may arrange for a Substitute Vehicle for completion of Your Ride to Your destination. However, the arrangement of Substitute Vehicle shall be subject to its availability.</p>

          <p>4.13. You acknowledge and agree that Substitute Vehicle may not be necessarily of the same type as the original Vehicle booked by You from the Site.</p>

          <p>4.14. Mybuggy Cabs bears no responsibility and liability for delays and losses suffered by You or caused to You as a consequence of the breakdown of the Vehicle or the Substitute Vehicle.</p>

          <p>4.15. The My Buggy Rideshare Platform is a tech aggregator or mediator Platform which facilitates distributed riders/passengers/users with drivers with which the best way they can move around. Individuals who wants to be My Buggy partner can simply download the app, register and become My Buggy Partner right away, and can work from anywhere, anytime 24/7 wherever My Buggy Platform allows. My Buggy Partner Drivers operates a private fleet of luxury cars and professional multi language speaking Partner drivers know their way around. Rider would be able to choose from a variety of offered car categories (Standard, SUV, Van, Mini) best suits your needs, set your destination and check the price before confirming. We commit to your fast transportation at the best price, whether it's an airport transfer, a trip to the beach or a night out, your ride will always be a click away! Request a ride now or plan ahead and schedule one for any time in the future.</p>
          <h2 className={h2}>5. CONFIRMATION OF BOOKING</h2>
          <p>5.1. Mybuggy Cabs shall, upon receiving the booking request from You in the manner set out above, proceed to confirm or decline the booking based on the availability of Vehicles at the pickup time, which shall be informed to You vide an SMS or email. In the event the booking is confirmed, You shall check the booking details including but not limited to pick up time and pick up place, and if there is incorrect detail, the same needs to be informed to us immediately by calling our call center.</p>

          <p>5.2. You shall bear the consequences and damages for any delay that may be caused to You due to Your failure to check the confirmation SMS or email or failure to inform Mybuggy Cabs of the incorrect details immediately.</p>


          <h2 className={h2}>6. PAYMENT</h2>
          <p>6.1. Mybuggy Cabs shall charge Convenience Fee or Access Fee for the Service which shall be determined and amended at the sole and absolute discretion of Mybuggy Cabs. The Convenience Fee or Access Fee shall be payable by you to Mybuggy Cabs and shall be informed to you before you begin your ride. It is Driver’s responsibility to collect Cash or through other digital mode of payment for Cash or Wallet payment or failed card payment and inform Help Desk Immediately. It is driver’s responsibility to make sure that the payment happens accordingly, else driver has to pay if it was drivers choice to mark the ride as complete at the end. Driver nee to take the drop off address and mark the ride as complete to make sure system charges. Collect Cash or Wallet to avoid scams.</p>

          <p>6.2. TPSP shall charge such amounts as may be informed to You by the TPSP if you opt for such services, from time to time.</p>

          <p>6.3. You shall be required to pay such Additional Fee, which will form part of the receipt of the Total Ride Fee.</p>

          <p>6.4. You shall be required to pay such Cancellation Fee in terms of Clause 7, which will form part of the receipt of the Total Ride Fee.</p>

          <p>6.5. In addition to the Total Ride Fee, You may be required to pay such other charges incurred by you during the Ride in cash i.e. Additional Fee, which are not included in the receipt of the Total Ride Fee.</p>

          <p>6.6. The Total Ride Fee will be collected by the Driver or Mybuggy Cabs from You at the end of the Ride, as set out in Clause 6.9 below.</p>

          <p>6.7. Mybuggy Cabs shall provide a receipt of the Total Ride Fee payable by You at the end of the Ride, however, separate invoices raised by the TPSPs for the Fare and Additional Fee, and the Convenience Fee or Access Fee raised by Mybuggy Cabs shall be provided to You on request. You may raise a request for a copy of the invoices from our Support page.</p>

          <p>6.8. All applicable taxes in respect of the Fare, Convenience Fee, Additional Fee, Cancellation Fee shall be borne and payable by You to the TPSPs or Mybuggy Cabs, as the case may be.</p>

          <p>6.9. You shall choose to pay for the Service Fee by either of the following four methods:
            (i) Cash payment: Cash payment towards the Total Ride Fee after the completion of Ride can be made to the Driver.
            (ii) E-Wallet payment: Mybuggy Cabs offers You the facility of making an online payment through an E-Wallet powered by a third party payment processor (“Payment Processor”). E-Wallet money will not be applicable on bookings made through the phone or while the user is not logged into his/her Account on the Site. The processing of payments, in connection with Your use of the E-Wallet will be subject to the terms, conditions, and privacy policies of the Payment Processor that Mybuggy Cabs engages for the purpose. Mybuggy Cabs will not be responsible for any errors by the Payment Processor in any manner. Further, even in cases of E- Wallet payments, all Additional Fee (defined below) shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. When You choose to make an E-Wallet payment, Mybuggy Cabs shall collect the Fare on behalf of the Driver/ TPSP who will be responsible for providing the such Services.
            (iii) Mybuggy Cabs Credit Payment: Payment for the Total Ride Fee can be made to Mybuggy Cabs on credit subject to the terms provided at https://s3-ap-southeast-1.amazonaws.com/Mybuggy Cabs-prod-website/TERMS+AND+CONDITIONS_Mybuggy CABS+CREDIT.pdf Further, even in cases of Mybuggy Cabs Credit payments, all Additional Fee shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. When You choose to make an Mybuggy Cabs Credit payment, Mybuggy Cabs shall collect the Fare on behalf of the Driver/ TPSP who will be responsible for providing the transportation services.
            (iv) Credit Card/ Debit Card/ Net Banking Payment: Total Ride Fee shall be effected using the services of an entity providing payment gateway/processor services (“PG”), authorized by Mybuggy Cabs. Such PG may either be Mybuggy Cabs or any of its affiliates or partners or unrelated third parties. You agree and undertake to share relevant payment details including credit/debit card details (Card Details) with the PG for the successful completion of payment towards Total Ride Fee to Mybuggy Cabs and authorize the PG to complete such transactions. In this respect, it is clarified that all PGs whose services are utilized for the purposes of the Site and/or Application and/or Services shall be PCI-DSS (Payment Card Industry – Data Security Standard) compliant. Your authorization permits the PG to debit or credit the bank account associated with Your payment details. Your authorization further permits the PG to use Your Card Details for the processing of transactions initiated by You at any of Mybuggy Cabs’s affiliates. Your authorization will remain in effect as long as You maintain an Account with Us. In the event You delete Your Card Details with the PG or if You delete Your Account, the PG will not process any further transactions initiated by You at the Site or Application and at the sites of any of Mybuggy Cabs’s affiliates. Your authorization under this clause is subject to any other terms and conditions of the PG.</p>

          <p>6.10. Any payment related issue, except when such issue is due to an error or fault in the Site, shall be resolved between You and the Payment Processor. Mybuggy Cabs shall not be responsible for any unauthorized use of Your E-Wallet during or after availing the Services on the Site.</p>

          <p>6.11. Driver would be able to do cash out anytime, but driver need to give enough time to the help desk team to calculate, recheck and process. It would be paid either through zelle, Cash App or any other mode of payment.</p>


          <h2 className={h2}>7. CANCELLATION POLICY</h2>
          <p>7.1. You agree and acknowledge that You may cancel Your request for a Vehicle from a Driver at any point of time subject to a Cancellation Fee as explained below:</p>

          <ul>
            <li>If you cancel after 5 minutes after the cab is allotted or</li>
            <li>If a driver cancels after waiting at Your location for more than 10 minutes</li>
            <li>Notwithstanding the foregoing, if the Driver is delayed by more than five (5) minutes to pick You, You will not be charged any Cancellation Fee.</li>
          </ul>

          <p>7.2. You shall be notified of the applicable Cancellation Fee in advance whenever You attempt to cancel a booking/service request. The notification shall be on the Application and/or the Site.</p>

          <p>7.3. Mybuggy Cabs shall provide a receipt of the Cancellation Fee, if any, payable by You for every cancellation in terms of the table above for such cancellations, however, separate invoices raised by the TPSPs for the Cancellation Fee, and Mybuggy Cabs for the Convenience Fee on cancellations shall be provided to You on request. You may raise a request for a copy of the invoices from the Support page.</p>

          <p>7.4. The Cancellation Fee shall be payable by You at the completion of Your subsequent Ride.</p>

          <p>7.5. The mode of payment of the Cancellation Fee shall be in terms of Clause 7 of these User Terms.</p>

          <p>7.6. This Clause 7 shall not apply to corporate rides availed pursuant to the terms and conditions.</p>

          <h2 className={h2}>8. Drug, Alcohol, Sex or any such violation Policy:</h2>

          <p>8.1. You shall not smoke and drink in the Vehicles or misbehave with the Driver or distract the Driver or act.</p>

          <p>In the event You are found to be involved in the activities set out above,</p>

          <p>You shall be liable to pay a fine to us and we shall also have the right to terminate the Ride. In the event You fail to pay fine after the completion of the Ride, we may at our discretion, take such steps as may be available to us under Applicable Law. You shall also be blacklisted as a result of non-payment of the fine or misbehaving as the case may be, and in such event, Your Account may be terminated by Mybuggy Cabs. Easy Taxi has a zero tolerance policy on the user of drug or alcohol while the driver is providing TNC services, Drivers will be made aware of this policy and will be required to affirmatively acknowledge this policy. Driver’s candidature would be immediately suspending with access to our platform revoke with immediate effect upon receipt of a passenger complaint allegation a violation of the zero-tolerance policy and such such suspension shall last the duration of the applicant’s investigation.</p>

          <h2 className={h2}>9. CUSTOMER RELATIONSHIP MANAGEMENT</h2>
          <p>
            9.1. All issues, opinions, suggestions, questions and feedback while availing our Services shall be communicated to us through email address mentioned in Clause 22.2. In case of a Ride booked on our Application, You shall be required to rate the Ride after its termination. You agree to be fair, accurate and non-disparaging while leaving comment, feedbacks, testimonials or reviews on or about the Rides or Services.
          </p>

          <p>
            9.2. Reporting of any issue needs to be within 7 (seven) days of the happening of the issue, failing which, such issue will not be addressed.
          </p>

          <p>
            9.3. Any issue reported on channels other than the above may be addressed by Mybuggy Cabs only on a best-effort basis. Mybuggy Cabs takes no liability for inability to get back on other channels.
          </p>

          <p>
            9.4. Mybuggy Cabs shall endeavor to respond to Your issues within 2 (two) working days of Your reporting the same and endeavor to resolve it at the earliest possible. It is hereby clarified that issues are resolved on severity basis, and certain may be resolved earlier than the other. However, Mybuggy Cabs shall not be liable for any damages or losses in the event You are not satisfied with any such resolution.
          </p>


          <h2>10. EMERGENCY SERVICES TO CUSTOMER</h2>
          <p>
            10.1 By accepting these User Terms and on pressing the SOS button on the Mybuggy Cabs App, You consent to Mybuggy Cabs using its best endeavors to provide You with assistance during a safety incident, emergencies or distress, as per Mybuggy Cab’s internal policies on emergency response. Mybuggy Cabs may undertake remedial action(s), including, but not limited to the following:
          </p>

          <p>
            10.1.1 When you press the SOS button and report a safety incident, the Mybuggy Cabs representative may escalate the incident internally or liaise with any third party security service providers to assist You and/or deploy response teams to Your location. It has the option to call 911 for emergency, before 911 you have the option to call Easy Taxi Customer care through your mobile app, talk to easy taxi helpdesk over chat, email, submit form from website. You may be able to save your family or friends contact number in speed dial list for emergency assistance. you would be able to share your current location through social media as well as regular text for emergency.
          </p>

          <p>
            10.1.2 Mybuggy Cabs may inform any government authorities, such as the concerned police station, about the incident and seek their assistance; Mybuggy Cabs may also provide such authority(ies) with your personal information including but not limited to your exact GPS location, your registered email ID and mobile number to enable them to take appropriate steps to assist You.
          </p>

          <p>
            10.1.3 Mybuggy Cabs may engage third party security providers to assist You and Mybuggy Cabs in addressing the incident. For this purpose, Mybuggy Cabs may share your personal information, including but not limited to, your exact GPS location, your registered email ID and mobile number with third parties such as a security services provider, to enable them to take appropriate steps to assist You and solely to resolve the incident.
          </p>

          <p>
            10.1.4 Further to the above, You may receive telephone calls from an Mybuggy Cabs representative and/or the relevant response team at the time of pressing the SOS button and in the duration that the incident is being resolved, and the same shall not be construed as breach of Regulatory guidelines, in as much as these would be made for Your security and safety purposes.
          </p>

          <p>
            10.2 Under this clause, You give Your express consent to permit Mybuggy Cabs to undertake the above along with any ancillary actions that may be required to facilitate an effective emergency response.
          </p>

          <p>
            10.3 Mybuggy Cabs will not be liable for any deficiency of service, provided to You under this clause on a best efforts basis, and this clause does not, in any manner, restrain You from seeking any other form of assistance from any other party.
          </p>

          <h2>11. FORCE MAJEURE</h2>
          <p>
            11.1 We shall not be liable for any failure to perform any obligations under this User Terms, if the performance is prevented, hindered or delayed by a Force Majeure Event and in such case our obligations under this User Terms shall be suspended for so long as the Force Majeure Event continues.
          </p>

          <h2>12. INDEMNIFICATION</h2>
          <p>
            12.1 By accepting these User Terms and using the Service, You agree that You shall defend, indemnify and hold Mybuggy Cabs, its affiliates, their licensors, and each of its officers, directors, other users, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses.
          </p>

          <h2>13. LIABILITY</h2>
          <p>
            13.1. The information, recommendations and/or Services provided to You on or through the Site, the Application and Mybuggy Cabs call center are for general information purposes only and does not constitute advice. Mybuggy Cabs will reasonably keep the Site and its contents correct and up to date but does not guarantee that (the contents of) the Site is free of errors, defects, malware and viruses or that the Site is correct, up to date and accurate.
          </p>

          <p>
            13.2. Mybuggy Cabs shall not be liable for You missing trains/flights/events or delays etc. as the Service is dependent on many factors not in Mybuggy Cab’s control. You must book Your Ride after taking into account the check-in time, traffic and weather conditions, political rallies, natural calamities, traffic barricades, car breakdowns and other un-expected delays.
          </p>

          <p>
            13.3. In the event, there is a delay by the Vehicle in reaching the pickup location beyond 30 (thirty) minutes of the pickup time, Mybuggy Cabs shall only endaveour to get You in touch with the Driver assigned for Your Ride.
          </p>

          <p>
            13.4. Mybuggy Cabs shall not be liable for any damages resulting from the use of or inability to use the Site, including damages caused by wrong usage of the Site, error in call center number, network issues, malware, viruses or any incorrectness or incompleteness of the Information or the Application.
          </p>

          <p>
            13.5. You shall take full responsibility of Your items and luggage. In case of lost items inside the Vehicle during the journey, Mybuggy Cabs will try to locate the items on a “best-effort” basis but is not responsible for the same in case of loss or damage to the same. If You leave any goods in the Vehicle or have any complaint in respect of the Services or the use of the Vehicle, You have to inform Mybuggy Cabs of the same in writing within 24 (twenty four) hours of using the Vehicle or the Services of Mybuggy Cabs. In the event it is found, You shall be informed about the Mybuggy Cabs office from where You can collect it after 3 (three) working days from the date You were informed. Mybuggy Cabs however shall not be responsible for delivering the same back to You. If requested, Mybuggy Cabs may deliver the misplaced item/s back to You after 3 (three) working days from the date You were informed, subject to the place of delivery being Ten (10) miles from the Mybuggy Cabs office. Mybuggy Cabs shall charge You a flat fee of $ 20 for such delivery.
          </p>

          <p>
            13.6. Mybuggy Cabs does not assure a complete sustainability of its Service and shall not be held responsible or liable for the same, in any manner.
          </p>

          <p>
            13.7. Mybuggy Cabs shall not be responsible for any loss of communication / information of status update and benefits under the program. All this information will be sent on mobile number and/or email ID registered with Mybuggy Cabs. Mybuggy Cabs will not be responsible for appropriateness of mobile or email or any other communication medium. You shall be responsible for immediately reporting the errors, if any, occurred in the information sent to You regarding booking confirmation.
          </p>

          <p>
            13.8. IN NO EVENT SHALL Mybuggy CABS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OR FOR ANY DAMAGES WHATSOEVER, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF Mybuggy CABS HAS BEEN ADVISED OF THE POSSIBILITY THEREOF.
          </p>

          <p>
            13.9. IN ADDITION, AND WITHOUT LIMITING THE FOREGOING, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL Mybuggy CABS’s AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE USER TERMS OR THE SERVICES RENDERED HEREUNDER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE, PRODUCT LIABILITY, OR OTHER THEORY), WARRANTY, OR OTHERWISE, EXCEED THE AMOUNT OF $. 10- (Ten Dollar).
          </p>

          <p>
            13.10. If Applicable Law does not permit the exclusion of certain warranties or the limitation or exclusion of liability, the scope and duration of such warranty exclusions and the extent of the liability of Mybuggy Cabs shall be the minimum permitted under Applicable Law.
          </p>

          <h2>14. APPLICATION LICENSE</h2>
          <p>
            14.1. Subject to Your compliance with these User Terms, Mybuggy Cabs grants You a limited, revocable, non-exclusive, non-transferable and non-sub-licensable license to download and install a copy of the Application on a single mobile device that You own or control and to run such copy of the Application solely for Your own personal use and to use the Site.
          </p>

          <p>

          </p>

          <p>
            14.3. You shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of Applicable Laws; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Service or the data contained therein; or (v) attempt to gain unauthorized access to the Service or its related systems or networks.
          </p>

          <p>
            14.4. Mybuggy Cabs will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. Mybuggy Cabs may involve and cooperate with law enforcement authorities in prosecuting Users who violate these User Terms. You acknowledge that Mybuggy Cabs has no obligation to monitor Your access to or use of the Service or the Site, but has the right to do so for the purpose of operating the Service or Site, to ensure Your compliance with these User Terms, or to comply with Applicable Law or the order or requirement of a court, administrative agency or other governmental body.
          </p>

          <p>
            14.5. Mybuggy Cabs reserves the right at all times to modify or discontinue, temporarily or permanently, Your access to or use of the Service or the Site with or without notice.
          </p>

          <p>
            14.6. Except as expressly stated herein, nothing in these User Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time.
          </p>

          <h2>15. MISCELLANEOUS</h2>
          <p>
            15.1. If any provision of these User Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under Applicable Law, and such provision shall be reformed to the minimum extent necessary to make such provision valid and enforceable.
          </p>

          <p>
            15.2. Mybuggy Cabs’s failure to enforce any right or provision in these User Terms shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Mybuggy Cabs in writing.
          </p>

          <p>
            15.3. These User Terms constitute the entire agreement between You and Mybuggy Cabs with respect to the Service and supersede all prior or contemporaneous communications and proposals, whether electronic, oral or written, between You and Mybuggy Cabs with respect to the Service.
          </p>

          <p>
            15.4. You may not assign or transfer these User Terms or Your rights hereunder, in whole or in part, by operation of law or otherwise, without Mybuggy Cabs’s prior written consent. We may assign these User Terms at any time without notice or consent.
          </p>

          <p>
            15.5. The section titles in these User Terms are for convenience only and have no legal or contractual effect.
          </p>

          <p>
            15.6. The word “including” means “including without limitation”.
          </p>

          <p>
            15.7. Notices to You may be made via email or regular mail or through the Application or Site. Mybuggy Cabs may also provide notices of changes to these User Terms or other matters by displaying notices or links to notices to You generally on the Service.
          </p>

          <p>
            15.8. Mybuggy Cabs shall not be responsible for Your acts or deeds by the service Mybuggy Cabs rendering to you and for any loss to Your accounts through Mybuggy cabs and external integrated accounts.
          </p>

        </div>
      </div>
    </div>
  );
};

export default TermsConditionsDriver;